"""Architecture-independent runtime contracts.

P2.1 defines serializable intent, observation, capability, context, error,
protocol, state-envelope, and reporting concepts. It does not select or execute
a backend.
"""

from radjax_student.runtime.errors import (
    RUNTIME_ERROR_CODES,
    RuntimeContractError,
    RuntimeErrorCode,
    RuntimeIssue,
)
from radjax_student.runtime.inspection import (
    RUNTIME_INSPECTION_CLAIMS_NOT_MADE,
    RUNTIME_INSPECTION_FINDING_CODES,
    InspectionStatus,
    RuntimeInspection,
    inspect_runtime_environment,
)
from radjax_student.runtime.keys import (
    RUNTIME_KEY_STREAM_NAMES,
    RUNTIME_KEYS_VERSION,
    RuntimeKeys,
    RuntimeKeyStream,
)
from radjax_student.runtime.models import (
    COMPILATION_POLICIES,
    DISTRIBUTED_POLICIES,
    FALLBACK_POLICIES,
    PLACEMENT_POLICIES,
    PRECISION_POLICIES,
    RUNTIME_CAPABILITY_VOCABULARY,
    CompilationOptions,
    CompilationPolicy,
    DeviceDescriptor,
    DeviceInventory,
    DistributedPolicy,
    ExecutionContext,
    FallbackPolicy,
    PlacementPolicy,
    PrecisionPolicy,
    RuntimeCapabilityProfile,
    RuntimeConfig,
    RuntimeEnvironment,
    RuntimeState,
    RuntimeStatus,
)
from radjax_student.runtime.protocols import RuntimeBackend
from radjax_student.runtime.registry import (
    SUPPORTED_RUNTIME_PLATFORMS,
    BackendAvailabilityStatus,
    FakeRuntimeBackend,
    JaxRuntimeBackend,
    RuntimeBackendAvailability,
    RuntimeBackendDescriptor,
    RuntimeBackendRegistry,
    build_default_runtime_registry,
)
from radjax_student.runtime.reports import RuntimeReport
from radjax_student.runtime.selection import (
    AUTOMATIC_PLATFORM_PREFERENCE,
    RUNTIME_SELECTION_CLAIMS_NOT_MADE,
    RUNTIME_SELECTION_WARNING_CODES,
    RuntimeSelectionResult,
    SelectionStatus,
    select_runtime_backend,
)
from radjax_student.runtime.smoke import (
    CPU_RUNTIME_SMOKE_CLAIMS_NOT_MADE,
    CPU_RUNTIME_SMOKE_WARNING_CODES,
    CpuRuntimeSmokeReceipt,
    CpuRuntimeSmokeStatus,
    default_cpu_smoke_config,
    run_selected_cpu_smoke,
    run_single_device_cpu_smoke,
)

__all__ = [
    "COMPILATION_POLICIES",
    "DISTRIBUTED_POLICIES",
    "FALLBACK_POLICIES",
    "PLACEMENT_POLICIES",
    "PRECISION_POLICIES",
    "RUNTIME_CAPABILITY_VOCABULARY",
    "RUNTIME_ERROR_CODES",
    "RUNTIME_INSPECTION_CLAIMS_NOT_MADE",
    "RUNTIME_INSPECTION_FINDING_CODES",
    "RUNTIME_KEYS_VERSION",
    "RUNTIME_KEY_STREAM_NAMES",
    "RUNTIME_SELECTION_CLAIMS_NOT_MADE",
    "RUNTIME_SELECTION_WARNING_CODES",
    "CPU_RUNTIME_SMOKE_CLAIMS_NOT_MADE",
    "CPU_RUNTIME_SMOKE_WARNING_CODES",
    "SUPPORTED_RUNTIME_PLATFORMS",
    "AUTOMATIC_PLATFORM_PREFERENCE",
    "BackendAvailabilityStatus",
    "CompilationOptions",
    "CompilationPolicy",
    "CpuRuntimeSmokeReceipt",
    "CpuRuntimeSmokeStatus",
    "DeviceDescriptor",
    "DeviceInventory",
    "DistributedPolicy",
    "ExecutionContext",
    "FakeRuntimeBackend",
    "FallbackPolicy",
    "InspectionStatus",
    "JaxRuntimeBackend",
    "PlacementPolicy",
    "PrecisionPolicy",
    "RuntimeBackend",
    "RuntimeBackendAvailability",
    "RuntimeBackendDescriptor",
    "RuntimeBackendRegistry",
    "RuntimeCapabilityProfile",
    "RuntimeConfig",
    "RuntimeContractError",
    "RuntimeEnvironment",
    "RuntimeErrorCode",
    "RuntimeIssue",
    "RuntimeInspection",
    "RuntimeKeys",
    "RuntimeKeyStream",
    "RuntimeReport",
    "RuntimeSelectionResult",
    "RuntimeState",
    "RuntimeStatus",
    "SelectionStatus",
    "build_default_runtime_registry",
    "default_cpu_smoke_config",
    "inspect_runtime_environment",
    "select_runtime_backend",
    "run_selected_cpu_smoke",
    "run_single_device_cpu_smoke",
]
